MY_SUBDIRS=
MY_BIN= async-fibonacci diamond_hierarchy enum extern foo_snippet my_map my_string \
		thread_join vector_resize is_checks bool_size to_string member_function \
		pointer_base virtual_call_base ref_pointer_deduce virtual_function \
		destructor_call internal_static
MY_OBJECTS=

include ../makefile.common
