MY_SUBDIRS=
MY_BIN= async-fibonacci diamond_hierarchy enum extern foo_snippet my_map my_string \
		sizeof_empty_string_array thread_join vector_resize sizeof_virtual
MY_OBJECTS=

include ../makefile.common
