MY_SUBDIRS=

MY_BIN=alloc_norelease alloc_overwrite alloc_release block container dlopenleak \
	   fabs printchars printformat printperf retarray sizeof sizeof_static soffset \
	   sscanf unicode 

MY_OBJECTS=

include makefile.common
