CXXFLAGS=-g

MY_SUBDIRS=hackerrank max-sum-triangle
MY_BIN=blocking_queue c11-pingpong range_overlap skyline spiral-traverse shuffle_sum_nearest execute_task_in_dependency_order skyline
MY_OBJECTS=

include ../makefile.common
